Script updates for tooling
microsoft/fluentui-system-icons pull request #721
Opened 2024-05-28 17:18 UTC by willchavez

- diff.sh, now also downloads the previous versions of the updates file, and uses imagemagick to compare them.
- Generate HTML Report, python script that creates a replica of the visual-diff tool we use for icon updates

![icon_updates](https://github.com/microsoft/fluentui-system-icons/assets/4759601/4dd40a16-1e52-4e6e-b504-0c2c99216d1c)

2024-07-23 21:20 UTC, spencer-nelson commented on scripts/diff.sh
> +read -p "Enter the commit ID to: " commit_id_to
Is it possible to just run this with a from and no "to" so it runs to the current commit?

2024-07-23 21:21 UTC, spencer-nelson commented on scripts/diff.sh
> +# This script extracts files changed between two specified Git commit IDs and performs various file operations.
For this to work you have to be on a branch that has the specific commit ids as part of the branch history. Sometimes it just requires a git pull, sometimes you might have to check out another branch, but that's worth noting as a possible error.

2024-07-23 21:22 UTC, spencer-nelson commented on scripts/generate_html_report.py
> +svg_folder = input("Please enter the path to the SVGs folder: ")
can there be a default value to this so one can just hit enter and not have to add a path?

2024-07-23 21:24 UTC, spencer-nelson requested changes
The default values are a nicety, but I feel it's critical to include instructions about being on a valid branch. I've been caught by that too many times.

2024-08-26 16:00 UTC, willchavez commented
@spencer-nelson just made some updates, excellent suggestions. 💯

2024-09-04 16:56 UTC, spencer-nelson approved these changes

2024-09-05 17:43 UTC, merged